name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          runtime: node@^24.20.0

      - name: Install Deps
        run: pnpm ci

      - name: Build project
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --no-git-checks
