name: Test

on:
  push:
    branches:
      - main
      - work
  pull_request:
    branches:
      - main

jobs:
  test-demos:
    name: Test on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - "16"
          - "18"
          - "20"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Build project
        run: pnpm build

      - name: Linter test
        run: |
          pnpm lint

      - name: Unit test
        run: pnpm test

      - name: Upload coverage
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v3
